### ISSUE TITLE
Exclamation mark (!) in password causes command to break

### ISSUE THREAD

**Issue by kristijanhusak** [tpope/vim-db#1]
`DB` command fails when using this database url:

```
postgres://postgres:SuperSecure1!@192.168.99.100:5432/my-database
```

I get this error in preview window:

```
psql: invalid port number: "SuperSecure1mkdir ~"
```

Removing `!` from password fixes it.

**Comment by hoylemd** [comment]
Did this get fixed?

**Comment by tpope** [comment]
Yes.

**Comment by hoylemd** [comment]
Hmm. I was still seeing this behaviour on Monday.  I installed the plugin via Vundle a week ago. I was specifying the db conection string in a project-local vimrc like:
```vim
DB g:db = postgres://<username>@<hostname>:<password!>@<full_server_domain>/<db_name>
```

full error message:
psql: invalid port number: '<password!>@<full_server_domain>'

It might be the <username>@<hostname> username format though, not the ! in the password. (my server is set up to require the hostname on the username and I don't have any control over that)

**Comment by tpope** [comment]
Definitely the `@` in the username. URLs require you to escape it as `%40`.

**Comment by hoylemd** [comment]
Oooooh! wow, I can't believe I didn't think of that.  Thanks!
