### ISSUE TITLE
Name contains insufficient wordplay

### ISSUE THREAD

**Issue by treuherz** [tpope/vim-db#13]
# Expected behaviour
tpope repos should have names such that
```
let a = <word relating to purpose>
let b = <name of repo>
a =~ b && ("vim-" . a) != b  " should be true
```

# Actual behaviour
`"vim-" . "db" != "vim-db"` evaluates to false.

# Possible fix
Rename to **vim-birdbath**, **vim-bloodbath**, **vim-redbrick**, **vim-windbag**, **vim-deadbeef**, **vim-breadbox**, **vim-tidbit**, **vim-cardboard**...

_Edited to add_: [**vim-dadbod**](https://twitter.com/tpope/status/600676388467843072)

**Comment by modille** [comment]
I agree... so many great options from `grep -i db /usr/share/dict/words`

**Comment by tpope** [comment]
I sat on this plugin for literally 2 years before giving up on a good name. Can't believe I missed dadbod tho, ugh. Will decide whether to rename when I'm ready to release version 1.1.

**Comment by OriontheCat** [comment]
Like the new name.
