### ISSUE TITLE
Support :terminal

### ISSUE THREAD

**Issue by cema-sp** [tpope/vim-db#16]
What do you think about supporting Neovim `:terminal` command (as it is done in **vim-fugitive**  https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L729-L737)?

**Comment by tpope** [comment]
I might officially embrace `:terminal` one day. Until then, I think https://github.com/radenling/vim-dispatch-neovim is probably good enough.

**Comment by AtomToast** [comment]
I wanted to ask if this issue could be reopened since neovim has evolved a bit and using :terminal for most things honestly works really well. It feels kind of bad having to use two extra plugins.
