### ISSUE TITLE
Save login information inside of secure store

### ISSUE THREAD

**Issue by purpleP** [tpope/vim-db#18]
On macOS this could be keychain I guess. There are also options for Linux.

That's basically why I don't use dbext and created my own plugin that just pastes queries from vim buffer into specified tmux window in which command line database client is opened.

**Comment by tpope** [comment]
The whole plugin is a paper thin wrapper around command line database clients. However you are currently managing passwords for those could almost certainly be used for db.vim as well.

**Comment by purpleP** [comment]
@tpope I think I haven't made my point clear. I'm mostly concerned about security. No one should be able to get database password from accessing my computer. So if it will be saved in command line history or vim command line history or in some unencrypted file - that's a security problem. Plugin should either prompt for password securely every time for each database or store passwords in some keychain and ask for master password once.

**Comment by tpope** [comment]
The password won't appear in any history or persisted file, but it is saved in an internal in memory data structure you could get at if you really wanted to. However, I just tested with `psql` and it does the same thing.

```
$ psql ...
Password:
psql (9.6.8, server 9.6.3)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
postgres=# select 1;
 ?column?
──────────
        1
(1 row)
postgres=#
# provoke disconnect
postgres=# select 1;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Succeeded.
postgres=# select 1;
 ?column?
──────────
        1
(1 row)
```

So, it hangs onto the password to use for reconnect. If db.vim is too insecure for you, so is `psql`. (And probably most other command line clients, but I'm not going to test them.)

I'm not going to write a secure storage wrapper, but I'd be happy to provide hooks if you want to write one.

**Comment by purpleP** [comment]
@tpope I'm not familiar with `psql` enough to understand how can intruder stole password from it. Is password is `1` in this case?

**Comment by tpope** [comment]
No, the password was input at the `Password:` prompt, and remembered for when reconnecting (`The connection to the server was lost. Attempting reset: Succeeded.`). You'd need a C debugger or something to get it out of memory. So it's not *trivial* to get it, but possible for a skilled hacker. That same skilled hacker could pull the password out of Vim's memory too.

**Comment by purpleP** [comment]
@tpope Hmm... I didn't know that you can attach debugger and get meaningful results to a running non-instrumented app. I will check this out.

**Comment by tpope** [comment]
If a hacker has that level of access, they could also install a keylogger, so you're probably screwed regardless.
