### ISSUE TITLE
Character encoding issues

### ISSUE THREAD

**Issue by Alexgunning** [tpope/vim-db#7]
Using with mongodb im getting some strange character encodings 
{
  [37m"_id"[m: [32m"dd9a1b50-2198-11e8-a52e-611cb81aa9fd"[m,
  [37m"email"[m: [32m"225973d5d73fbb557b2f6b96a8c@gmail.com"[m,
  [37m"notifications"[m: [31m1[m,
  [37m"type"[m: [32m"student"[m,
  [37m"firstName"[m: [32m"POSTMAN"[m,
  [37m"lastName"[m: [32m"TEST"[m,
}

**Comment by tpope** [comment]
Those are ansi color codes. What sort of shenanigans do you have in `~/.mongorc.js`?

**Comment by Alexgunning** [comment]
Ah I see. Thanks so much. I am using the [mongo hacker](https://github.com/TylerBrock/mongo-hacker) plugin. It adds some nice coloring and formatting to the mongo shell.

**Comment by tpope** [comment]
Mongo hacker could easily check for a terminal before using color codes, if you want to pursue a solution on that end.

**Comment by Alexgunning** [comment]
Thanks for the suggestion. I'll look into trying to fix that myself.
