### ISSUE TITLE
E492: Not an editor command: Startmysql

### ISSUE THREAD

**Issue by reisnobre** [tpope/vim-db#8]
Erro while trying to connect with my MySql db.

`:DB mysql://root@localhost/[dbname]` gives me the prompt for the password and then fails.
This line `Error detected while processing function db#execute_command:` and the this line `E492: Not an editor command: Startmysql -h 'localhost' -u 'root' -p'password' 'database'`.

I'm dumb or this is a bug?

**Comment by wspurgin** [comment]
Do you have a command string after that? I.e.
```
:DB mysql://root@localhost/[dbname] select * from my table
```

It needs a command after the connection string

**Comment by reisnobre** [comment]
As turns out, I'm just dumb...
Closing issue...

**Comment by tpope** [comment]
Accidentally added a dot after Start in
https://github.com/tpope/vim-db/commit/2b303d6802b6d88c7e16bcb806c0ed375820c94c.
AFK so a someone please PR a removal.

**Comment by tpope** [comment]
I think I fixed it from my phone. Please double check.

**Comment by wspurgin** [comment]
@reisnobre You're not dumb! I didn't know there was an interactive version. @tpope yup you fixed it from your phone. Just tested master
