### ISSUE TITLE
Connection over ssh

### ISSUE THREAD

**Issue by Kudlaty01** [tpope/vim-db#9]
Sometimes databases are available only via a ssh server and then can be accessed with host specified as localhost. 
I would like do ask if it is possible to access such database with this plugin.

BTW, Great plugin, so are many others from your foundry!

**Comment by denzuko** [comment]
couldn't one just do a ssh tunnel instead then point the address to localhost?

the idea is like this;

 1) `ssh -n -L3389:localhost:3389 mysql@example.com &`
 2) `vim +DB`

1. establishs the tunnel to example.com
2. launches vim then calls this plugin

**Comment by denzuko** [comment]
couldn't one just do a ssh tunnel instead then point the address to localhost?

the idea is like this;

 1) `ssh -n -L3389:localhost:3389 mysql@example.com &`
 2) `vim +DB`

1. establishs the tunnel to example.com
2. launches vim then calls this plugin

connect with mysql://dbuser@localhost/appdb

**Comment by Kudlaty01** [comment]
That is all correct, came up to it this morning and when wanted to share the knowledge I saw you've already posted with a very convenient completion. Thank you very much.

**Comment by ibotty** [comment]
The problem with doing it that way, is that if you have many tunnels, you will have to remember the port number.

One other possible way when there is no vpn (wireguard is easy to setup btw) is to use sshuttle. When forwarding only that one host, and the connection at the other side is not only listening on localhost (or ipc) you can just use the regular ip/hostname of the remote service.

**Comment by tpope** [comment]
You could make an adapter that supports URLs like `ssh:user@host:mysql://...` if you wanted to.

**Comment by ibotty** [comment]
Can one make a meta-wrapper that wraps any DB, because it might make sense to share that code.

**Comment by tpope** [comment]
Yes, the idea is to delegate anything after the second colon to the underlying adapter and prepend `ssh user@host` to it. I'm not going to write it myself.

**Comment by ibotty** [comment]
I was not demanding that! I'll have a look at what writing an adapter means...

**Comment by ianchanning** [comment]
My attempts at getting `ssh -n -L` to work failed. In the end I followed this [SSH tunnel guide](https://www.kevssite.com/connect-to-postgresql-using-an-ssh-tunnel/), which is very slightly different (I'm using an azure server that exposes Postgres on port 3121):

1. Open a SSH tunnel via `ssh -L5432:localhost:3121 user@my-server.westeurope.cloudapp.azure.com`
2. Open a new terminal an start vim
3. Connect with `:DB w:db = postgres://username:password@localhost/dbname`

**Comment by tpope** [comment]
What does "failed" mean?

Does it work with `psql` at the command line?

**Comment by ianchanning** [comment]
Errr... at the risk of showing my complete noobiness, I get this output. But no, `psql` doesn't work either. I'm sure it's nothing to do with Vim, just my lack of understanding with SSH tunneling. It crashes just trying to connect psql to the port I've forwarded.

```
channi16@ICT0115123:~$ ssh -n -L3121:localhost:3121 user@my-server.westeurope.cloudapp.azure.com &
[1] 16221
channi16@ICT0115123:~$ Pseudo-terminal will not be allocated because stdin is not a terminal.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.3.0-1035-azure x86_64)

[... the standard Ubuntu terminal welcome messages ...]

psql --port=3121
psql: error: could not connect to server: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.3121"?
[1]+  Done                    ssh -n -L3121:localhost:3121 user@my-server.westeurope.cloudapp.azure.com
```

**Comment by pbogut** [comment]
I don't think `ssh://` adapter can be written. At least not for everything, for example mysql adapter [here](https://github.com/tpope/vim-dadbod/blob/fb543e602de2fe74a7928c78e152bb964abb7a9a/autoload/db/adapter/mysql.vim#L46) and [here](https://github.com/tpope/vim-dadbod/blob/fb543e602de2fe74a7928c78e152bb964abb7a9a/autoload/db/adapter/mysql.vim#L51)
 is using `system()` function call, so there is no way to wrap it with `ssh ... -t`. Not sure about other adapters.

**Comment by tpope** [comment]
Adapter would need to use `-t` for `#interactive()` but _not_ for `#filter()`. There may be other edge cases that are harder to work around.

@ianchanning psql is still using a UNIX socket, you'll need to find the incantation that forces it to use TCP.

**Comment by antosha417** [comment]
In my scenario, using an SSH tunnel might not be feasible, as I lack direct access to the machine hosting the database. However, I do have access to another machine, which is on the whitelist and can query the database.

Do you know if can I establish a connection to the database in this setup?

I would greatly appreciate any guidance here, thank you in advance 

Thank you for your insights!

**Comment by tpope** [comment]
> In my scenario, using an SSH tunnel might not be feasible, as I lack direct access to the machine hosting the database. However, I do have access to another machine, which is on the whitelist and can query the database.
> 
> Do you know if can I establish a connection to the database in this setup?

The ssh command would look like this:

```
ssh -n -L3389:actual-db-host:3389 machine-on-the-whitelist
```

**Comment by denzuko** [comment]
@tpope Think this issue might need to be locked since that's the same answer I gave earlier on [March 9th, 2018](https://github.com/tpope/vim-dadbod/issues/9#issuecomment-371673318). Seems to me people are just asking to ask at this point instead of reading the solution.

**Comment by tpope** [comment]
Not quite the same, there was confusion about what to do when you couldn't ssh directly to the db host. (Answer: swap out `localhost`.)
